version: '3.8'

services:
  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: entreprise_manager
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php
    ports:
      - "9001:9001"  # Symfony Server
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network
    depends_on:
      - mysql

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: node
    ports:
      - "3000:3000"  # React Development Server
    volumes:
      - ./frontend:/app
    networks:
      - app-network
    depends_on:
      - php
    command: ["npm", "run", "start"]

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"  # Port SMTP
      - "8025:8025"  # Interface Web
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge