version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: node
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - php

volumes:
  mysql_data: